### ISSUE TITLE
Review outdated and unneeded project dependencies

### ISSUE THREAD

**Issue by internetisaiah** [kobiton/docs#127]
### Issue description

Run `yarn outdated` to review outdated and unneeded project dependencies found in `package.json` and `yarn.lock`.

**Tasks:**
- [ ] Replace `gulp-vinyl-zip@2.5.0`. Impacts `@antora/file-publisher` and `@antora/ui-loader` in `@antora/site-generator`.
- [ ] Upgrade `@mermaid-js/mermaid-cli`.
- [ ] Remove `mermaid.cli@0.5.1`. `@mermaid-js/mermaid-cli` can be used instead.
- [ ] Either upgrade or remove `@sntke/antora-mermaid-extension`, depending if same functionality is built in to `@mermaid-js/mermaid-cli`.
- [ ] Either upgrade or remove `mermaid`, depending if same functionality is built in to `@mermaid-js/mermaid-cli`.
